const axios = require('axios');

const baseUrl = 'http://localhost:5000/keywords';

const keywordDict = {
    food: [
        "Culinary Arts",
        "Gastronomic Delights",
        "Foodie Adventures",
        "Gourmet Cuisine",
        "Culinary Exploration",
        "Tasty Recipes",
        "Cooking Mastery",
        "Flavorful Dishes",
        "International Cuisine",
        "Epicurean Pleasures",
        "Nutrient-rich Foods",
        "Cooking Hacks",
        "Culinary Creativity",
        "Fusion Flavors",
        "Delectable Treats",
        "Culinary Excellence",
        "Spice Infusion",
        "Farm-to-Table",
        "Dessert Paradise",
        "Savoring Moments",
    ],
    sports: [
        "Athletic Achievements",
        "Sporting Events",
        "Fitness Pursuits",
        "Sportsmanship",
        "Training Regimens",
        "Victory Moments",
        "Adrenaline Rush",
        "Competitive Spirit",
        "Sports Legends",
        "Team Dynamics",
        "Extreme Sports",
        "Sports Culture",
        "Peak Performance",
        "Championship Glory",
        "Sports Spectacles",
        "Fitness Lifestyle",
        "Sports Gear Innovation",
        "Sports Diversity",
        "Sporting Challenges",
        "Sports Psychology",
    ],
    travel: [
        "Wanderlust Journeys",
        "Travel Exploration",
        "Cultural Odyssey",
        "Adventure Escapes",
        "Passport Adventures",
        "Hidden Gems",
        "Travel Diaries",
        "Globe-trotting Tales",
        "Travel Photography",
        "Journey Discoveries",
        "Local Experiences",
        "Travel Essentials",
        "Sustainable Travel",
        "Backpacking Adventures",
        "Travel Wanderings",
        "Road Trip Wonders",
        "Remote Destinations",
        "Tropical Paradises",
        "Urban Explorations",
        "Travel Inspiration",
    ],
    music: [
        "Melodic Harmony",
        "Musical Genres",
        "Rhythmic Beats",
        "Concert Experiences",
        "Harmony Fusion",
        "Musical Innovation",
        "Chart-topping Hits",
        "Musical Legends",
        "Soundscapes",
        "Album Masterpieces",
        "Jazz Exploration",
        "Indie Melodies",
        "Music Festivals",
        "Acoustic Bliss",
        "Lyrics Unleashed",
        "Classical Resonance",
        "Songwriting Artistry",
        "Pop Culture Sounds",
        "Musical Diversity",
        "Live Performances",
    ],
    fitness: [
        "Wellness Journey",
        "Fitness Motivation",
        "Workout Routines",
        "Wellness Lifestyle",
        "Holistic Health",
        "Mind-Body Balance",
        "Active Living",
        "Fitness Challenges",
        "Body Positivity",
        "Health Transformation",
        "Cardio Workouts",
        "Strength Training",
        "Yoga Bliss",
        "Mental Fitness",
        "Healthy Habits",
        "Wellness Tips",
        "Exercise Diversity",
        "Fitness Inspiration",
        "Outdoor Fitness",
        "Balanced Living",
    ],
    automobile: [
        "Automotive Excellence",
        "Drive Safely",
        "Car Enthusiast",
        "Road Adventures",
        "Auto Innovation",
        "Motor Performance",
        "Driving Experiences",
        "Luxury Rides",
        "Automotive Design",
        "Road Trip Essentials",
        "Car Technology",
        "Eco-friendly Driving",
        "Car Culture",
        "Auto Maintenance",
        "Driving Thrills",
        "Classic Cars",
        "Roadside Views",
        "Car Accessories",
        "Racing Passion",
        "Road-Tested",
    ],
    gadget: [
        "Tech Gadgets Galore",
        "Innovation Hub",
        "Gadget Exploration",
        "Futuristic Tech",
        "Cutting-edge Devices",
        "Tech Marvels",
        "Digital Lifestyle",
        "Gadget Trends",
        "Smart Living",
        "Electronic Marvels",
        "Geek Culture",
        "Technological Wonders",
        "Gadget Reviews",
        "Wearable Tech",
        "Home Automation",
        "Tech Breakthroughs",
        "Consumer Electronics",
        "App Revolution",
        "Virtual Reality",
        "Gaming Gadgets",
    ],
    technology: [
        "Tech Innovations",
        "Emerging Tech Trends",
        "Digital Transformation",
        "Information Technology",
        "Tech Insights",
        "Cybersecurity",
        "Tech Impact",
        "Data Revolution",
        "AI Advancements",
        "Robotics Realm",
        "Cloud Computing",
        "Internet of Things (IoT)",
        "Future Tech",
        "Tech Ethos",
        "Digital Revolution",
        "Tech Solutions",
        "Tech Integration",
        "Science and Tech",
        "Innovative Systems",
        "Tech Visionaries",
    ],
};

async function addKeyword(category, value, level) {
    try {
        const response = await axios.post(baseUrl, {
            category,
            value,
            level,
        });

        console.log(`Keyword added: ${value} - Category: ${category}`);
    } catch (error) {
        console.error(`Error adding keyword: ${value} - Category: ${category}`);
        console.error(error.message);
    }
}

for (const category in keywordDict) {
    const keywords = keywordDict[category];

    for (const keyword of keywords) {
        await addKeyword(category, keyword, 2);
    }
}
