const {
  PrismaClient,
} = require('@prisma/client');
const prisma = new PrismaClient();

const newKeywords = {
  sports: [
    'Archery',
    'Air Racing',
    'Athletics',
    'Backstroke',
    'Badminton',
    'Baseball',
    'Basketball',
    'Benchpress',
    'Bicycle Motocross (BMX)',
    'Billiards',
    'Bodybuilding',
    'Bowling',
    'Boxing',
    'Camel Racing',
    'Canoe Slalom',
    'Chess',
    'Cricket',
    'Cycling',
    'Deadlifting',
    'Discus Throw',
    'Diving',
    'Drifting',
    'Equestrian',
    'Fencing',
    'Football',
    'MMA',
    'Formula F1 Racing',
    'Gliding',
    'Golf',
    'Gymnastics',
    'Handball',
    'High Jump',
    'Hockey',
    'Horse Racing',
    'Javelin Throw',
    'Judo',
    'Kabaddi',
    'Karate',
    'Long Jump',
    'Marathon',
    'Modern Pentathlon',
    'Netball',
    'Powerlifting',
    'Rugby',
    'Sailing',
    'Shooting',
    'Wrestling',
    'Shot Put',
    'Skateboarding',
    'Sport Climbing',
    'Surfing',
    'Swimming',
    'Table Tennis',
    'Taekwondo',
    'Tennis',
    'Triple Jump',
    'Triathlon',
    'Tug of War',
    'Volleyball',
    'Water Polo',
    'Weightlifting',
    'Pole Vault',
    'Snowboarding',
    'Skiing',
    'Biathlon',
    'Bobsleigh',
    'Cross-Country Skiing',
    'Curling',
    'Ice Skating',
    'Luge',
    'Skeleton',
    'Ski Jumping',
    'Speed Skating',
    'Alpine Skiing',
    'Nordic Combined',
    'Freestyle Skiing',
    'Snowboard Cross',
    'Paragliding',
    'Hang Gliding',
    'Motocross',
    'Mountain Biking',
    'Skimboarding',
    'Kite Surfing',
    'Windsurfing',
    'Bodyboarding',
    'Rowing',
    'Kayaking',
    'Canoeing',
    'Synchronized Swimming',
    'Polo',
    'Lacrosse',
    'Squash',
    'Racquetball',
    'Pickleball',
    'Darts',
    'Snooker',
    'Parkour',
    'Ultimate Frisbee',
    'Frisbee Golf',
    'Obstacle Course Racing',
    'Bouldering',
    'Rock Climbing',
    'Ice Climbing',
    'Ice Hockey',
    'Roller Hockey',
    'Inline Skating',
    'Skate Racing',
    'Rhythmic Gymnastics',
    'Trampoline',
    'Aerobic Gymnastics',
    'Artistic Swimming',
    'Synchronized Skating',
    'Capoeira',
    'Muay Thai',
    'Kickboxing',
    'Brazilian Jiu-Jitsu',
    'Sumo Wrestling',
    'Folk Wrestling',
    'Greco-Roman Wrestling',
    'Freestyle Wrestling',
    'Sambo',
    'Aikido',
    'Hapkido',
    'Kendo',
    'Taichi',
    'Wushu',
    'Krav Maga',
    'Silat',
    'Pencak Silat',
    'Esports',
    'Drone Racing',
    'Orienteering',
    'Adventure Racing',
    'Horseback Archery',
    'Equestrian Vaulting',
    'Polo Cross',
    'Bareback Riding',
    'Dressage',
    'Endurance Riding',
    'Horse Show Jumping',
    'Steeplechase',
    'Harness Racing',
    'Trotting',
    'Bull Riding',
    'Rodeo',
    'Calf Roping',
    'Barrel Racing',
    'Steer Wrestling',
    'Team Roping',
    'Breakaway Roping',
    'Goat Tying',
    'Underwater Hockey',
    'Underwater Rugby',
    'Scuba Diving',
    'Free Diving',
    'Spearfishing',
    'Underwater Photography',
    'Synchronized Diving',
    'Cliff Diving',
    'High Diving',
    'Platform Diving',
    'Springboard Diving',
    'Ice Fishing',
    'Fly Fishing',
    'Bass Fishing',
    'Deep Sea Fishing',
    'Surf Fishing',
    'Kite Flying',
  ],
  travel: [
    'Adventure Travel',
    'Backpacking',
    'Solo Travel',
    'Luxury Travel',
    'Cultural Tourism',
    'Eco-Tourism',
    'Sustainable Travel',
    'Wellness Tourism',
    'Voluntourism',
    'Cruise Travel',
    'Road Trips',
    'RV Travel',
    'Camping',
    'Glamping',
    'Beach Vacations',
    'Island Hopping',
    'Skiing Trips',
    'Snowboarding',
    'Mountain Climbing',
    'Hiking',
    'Trekking',
    'Wildlife Safari',
    'Bird Watching',
    'Scuba Diving',
    'Snorkeling',
    'Surfing',
    'Kayaking',
    'Canoeing',
    'White Water Rafting',
    'Sailing',
    'Yacht Charters',
    'Fishing Trips',
    'Hunting Expeditions',
    'Cycling Tours',
    'Motorcycle Touring',
    'Horseback Riding Tours',
    'Culinary Tourism',
    'Wine Tours',
    'Brewery Tours',
    'Distillery Tours',
    'Agritourism',
    'Farm Stays',
    'City Breaks',
    'Historical Tours',
    'Archaeological Tours',
    'Religious Pilgrimages',
    'Spiritual Retreats',
    'Yoga Retreats',
    'Meditation Retreats',
    'Art Tours',
    'Museum Tours',
    'Theater Trips',
    'Music Festivals',
    'Film Festivals',
    'Literary Tours',
    'Photography Tours',
    'Stargazing Trips',
    'Northern Lights Viewing',
    'Desert Safaris',
    'Jungle Expeditions',
    'Rainforest Tours',
    'Volcano Tours',
    'Geothermal Tours',
    'Hot Springs Visits',
    'Health and Wellness Spas',
    'Thermal Baths',
    'Couples Retreats',
    'Family Vacations',
    'Theme Park Visits',
    'Educational Travel',
    'Student Exchange Programs',
    'Study Abroad',
    'Language Immersion Programs',
    'Work Abroad',
    'Digital Nomad Lifestyle',
    'Gap Year Travel',
    'Ancestry Tourism',
    'Genealogy Travel',
    'Heritage Tours',
    'World War Battlefields Tours',
    'Holocaust Memorial Tours',
    'Cold War Sites Tours',
    'Space Tourism',
    'Underwater Hotels',
    'Treehouse Stays',
    'Castle Stays',
    'Haunted Tours',
    'Ghost Town Visits',
    'Extreme Sports Travel',
    'Paragliding',
    'Bungee Jumping',
    'Skydiving',
    'Ziplining',
    'Rock Climbing',
    'Mountaineering',
    'Ice Climbing',
    'Hang Gliding',
    'Windsurfing',
    'Kiteboarding',
    'Jet Skiing',
    'ATV Adventures',
    'Desert Dune Bashing',
    'Snowmobiling',
    'Dog Sledding',
    'Polar Expeditions',
    'Antarctic Cruises',
    'Arctic Voyages',
    'Island Castaway Experiences',
    'Jungle Survival Training',
    'Traditional Crafts Workshops',
    'Cultural Exchange Programs',
    'Homestays',
    'Bed and Breakfast Stays',
    'Boutique Hotels',
    'Eco-Lodges',
    'Rainforest Canopy Stays',
    'Underground Accommodations',
    'Cave Explorations',
    'Fossil Hunting Tours',
    'Paleontology Tours',
    'Astronomy Camps',
    'Scientific Research Expeditions',
    'Volcanology Tours',
    'Marine Biology Tours',
    'Conservation Volunteer Programs',
    'Wilderness Skills Workshops',
    'Outdoor Survival Courses',
    'Ethical Wildlife Encounters',
    'Elephant Sanctuaries Visits',
    'Orangutan Rehabilitation Center Visits',
    'Coral Reef Restoration Projects',
    'Shark Cage Diving',
    'Whale Watching',
    'Dolphin Encounters',
    'Bird of Prey Experiences',
    'Butterfly Gardens',
    'Botanical Garden Tours',
    'Agricultural Tours',
    'Cheese Making Workshops',
    'Chocolate Making Workshops',
    'Coffee Plantation Tours',
    'Tea Estate Tours',
    'Spice Farm Tours',
    'Olive Oil Tasting',
    'Truffle Hunting',
    'Foraging Expeditions',
    'Cooking Classes',
    'Baking Workshops',
  ],
  technology: [
    'Artificial Intelligence (AI)',
    'Machine Learning',
    'Deep Learning',
    'Neural Networks',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Robotics',
    'Autonomous Vehicles',
    'Drones',
    'Internet of Things (IoT)',
    'Smart Home Technology',
    'Wearable Technology',
    'Virtual Reality (VR)',
    'Augmented Reality (AR)',
    'Mixed Reality (MR)',
    'Blockchain',
    'Cryptocurrency',
    'Bitcoin',
    'Ethereum',
    'NFTs (Non-Fungible Tokens)',
    'Cybersecurity',
    'Ethical Hacking',
    'Data Encryption',
    'Cloud Computing',
    'Edge Computing',
    'Quantum Computing',
    'Big Data',
    'Data Analytics',
    'Data Mining',
    'Predictive Analytics',
    'Business Intelligence (BI)',
    '3D Printing',
    'Additive Manufacturing',
    'Nanotechnology',
    'Biotechnology',
    'Genetic Engineering',
    'CRISPR',
    'Stem Cell Research',
    'Renewable Energy',
    'Solar Power',
    'Wind Power',
    'Hydroelectric Power',
    'Geothermal Energy',
    'Biomass Energy',
    'Battery Technology',
    'Electric Vehicles (EVs)',
    'Hybrid Vehicles',
    'Fuel Cell Technology',
    'Wireless Charging',
    'Smart Grids',
    'Sustainable Technology',
    'Green Computing',
    'E-Waste Recycling',
    'Digital Twins',
    '5G Technology',
    '6G Research',
    'Satellite Internet',
    'Fiber Optics',
    'Telemedicine',
    'E-Health',
    'Wearable Health Devices',
    'Remote Monitoring',
    'Medical Imaging',
    'Precision Medicine',
    'Telepresence',
    'Video Conferencing',
    'Collaboration Tools',
    'Remote Work Technology',
    'E-Learning',
    'Digital Classrooms',
    'Online Education Platforms',
    'Virtual Labs',
    'Gamification',
    'Serious Games',
    'Augmented Reality Learning',
    'Virtual Reality Training',
    'Adaptive Learning Technology',
    'MOOCs (Massive Open Online Courses)',
    'E-Commerce Platforms',
    'Digital Marketing',
    'Social Media Analytics',
    'SEO (Search Engine Optimization)',
    'Content Management Systems',
    'Customer Relationship Management (CRM)',
    'Supply Chain Management',
    'Blockchain in Supply Chain',
    'Autonomous Warehouses',
    'Drone Delivery',
    '3D Printing in Manufacturing',
    'Smart Factories',
    'Industry 4.0',
    'Industrial Internet of Things (IIoT)',
    'Collaborative Robots (Cobots)',
    'Predictive Maintenance',
    'Digital Currency',
    'Mobile Payment Systems',
    'FinTech',
    'InsurTech',
    'RegTech',
    'Robo-Advisors',
    'Crowdfunding',
    'Peer-to-Peer Lending',
    'Contactless Payment',
    'Biometric Authentication',
    'Facial Recognition Technology',
    'Voice Recognition',
    'Gesture Control',
    'Eye Tracking',
    'Smart Cities',
    'Urban Mobility Solutions',
    'Intelligent Transportation Systems',
    'Smart Parking',
    'Waste Management Technology',
    'Water Purification Technology',
    'Air Quality Monitoring',
    'Urban Farming',
    'Vertical Farming',
    'Hydroponics',
    'Aeroponics',
    'Aquaponics',
    'Smart Fabrics',
    'Wearable Electronics',
    'E-Textiles',
    'Smart Clothing',
    'Adaptive Interfaces',
    'Human-Computer Interaction',
    'User Experience Design',
    'Virtual Assistants',
    'Chatbots',
    'Speech Synthesis',
    'Language Translation',
    'Digital Art',
    'Computer-Generated Imagery (CGI)',
    'Virtual Production',
    'Motion Capture',
    'Digital Music Production',
    'Podcasting',
    'Streaming Services',
    'E-Sports',
    'Gaming Technology',
    'Virtual Reality Gaming',
    'Augmented Reality Games',
    'Cloud Gaming',
    'Game Development',
    'Game Engines',
    'Procedural Content Generation',
    'Adaptive Game AI',
    'Haptic Feedback',
    'Spatial Audio',
    'Immersive Experiences',
    '3D Audio',
    'Virtual Reality Cinematography',
    '360-Degree Video',
    'Interactive Storytelling',
    'Digital Storyboards',
    'Artificial Intelligence in Film',
    'Virtual Set Design',
    'Deepfakes',
    'Synthetic Media',
  ],
  gadget: [
    'Smartphone',
    'Tablet',
    'Laptop',
    'Desktop Computer',
    'Smartwatch',
    'Fitness Tracker',
    'E-Reader',
    'Wireless Earbuds',
    'Noise-Cancelling Headphones',
    'Bluetooth Speaker',
    'Portable Charger',
    'Power Bank',
    'Wireless Charging Pad',
    'Smart Glasses',
    'Virtual Reality (VR) Headset',
    'Augmented Reality (AR) Glasses',
    'Action Camera',
    'Digital Camera',
    'DSLR Camera',
    'Mirrorless Camera',
    'Instant Camera',
    'Drone',
    'Smart Home Hub',
    'Smart Light Bulb',
    'Smart Thermostat',
    'Smart Lock',
    'Video Doorbell',
    'Home Security Camera',
    'Robot Vacuum',
    'Air Purifier',
    'Smart Scale',
    '3D Printer',
    'Gaming Console',
    'Handheld Gaming Device',
    'Streaming Device',
    'Smart TV',
    'Soundbar',
    'Home Theater System',
    'Projector',
    'Portable Projector',
    'Dash Cam',
    'GPS Navigation System',
    'Radar Detector',
    'Smart Car Charger',
    'Smart Water Bottle',
    'Electric Scooter',
    'E-Bike',
    'Hoverboard',
    'Smart Golf Club',
    'Wearable Camera',
    'GoPro',
    'Underwater Drone',
    'Fish Finder',
    'Trail Camera',
    'Weather Station',
    'Smart Garden System',
    'Electronic Key Finder',
    'Wireless Keyboard',
    'Wireless Mouse',
    'Graphics Tablet',
    'External Hard Drive',
    'Solid State Drive (SSD)',
    'USB Flash Drive',
    'Network Attached Storage (NAS)',
    'Wi-Fi Extender',
    'Mesh Wi-Fi System',
    'Smart Router',
    'Universal Remote Control',
    'Digital Pen',
    'Smart Notebook',
    'Voice Recorder',
    'Smart Pen',
    'Language Translator Device',
    'Portable Scanner',
    'Laser Pointer',
    'Solar Charger',
    'Wind-Up Radio',
    'Emergency Radio',
    'Hand-Crank Charger',
    'Biometric Padlock',
    'Fingerprint Scanner',
    'Smart Ring',
    'Fitness Shirt',
    'Smart Fabric',
    'Haptic Feedback Device',
    'Brain-Sensing Headband',
    'Sleep Tracker',
    'Smart Pillow',
    'Smart Mattress',
    'UV Sanitizing Device',
    'Smart Mug',
    'Temperature Control Mug',
    'Electronic Cigarette',
    'Vape Pen',
    'Smart Inhaler',
    'Blood Pressure Monitor',
    'Glucose Monitoring Device',
    'Heart Rate Monitor',
    'Oximeter',
    'Thermometer',
    'Smart Toothbrush',
    'Electric Toothbrush',
    'Water Flosser',
    'Hair Growth Helmet',
    'LED Light Therapy Device',
    'Facial Recognition System',
    '3D Scanner',
    'Hologram Projector',
    'Smart Mirror',
    'Interactive Whiteboard',
    'Digital Microscope',
    'Telescope with Computerized Tracking',
    'Weather Balloon Kit',
    'Geiger Counter',
    'Metal Detector',
    'Stud Finder',
    'Laser Measure',
    'Thermal Imaging Camera',
    'Moisture Meter',
    'Smart Plant Sensor',
    'Soil Tester',
    'Agricultural Drone',
    'Pet Tracker',
    'Smart Pet Feeder',
    'Automatic Pet Door',
    'Interactive Pet Toy',
    'Dog Training Collar',
    'GPS Dog Fence',
    'Aquarium Monitoring System',
    'Smart Bicycle Lock',
    'Bike Computer',
    'Bike Rearview Camera',
    'Helmet with Built-In Lights',
    'Smart Motorcycle Helmet',
    'Heated Clothing',
    'Cooling Vest',
    'Electric Skateboard',
    'One-Wheel Scooter',
    'Jetpack',
    'Personal Submarine',
    'Flying Car',
    'Smart Luggage',
    'Luggage Tracker',
    'Travel Adapter',
    'Portable Espresso Maker',
    'Travel Iron',
    'Electronic Organizer',
    'Smart Notebook',
    'Portable Language Translator',
    'Travel Drone',
    'Noise-Canceling Earplugs',
    'Inflatable Solar Light',
    'Portable Water Filter',
    'Survival Gadgets',
    'Tactical Flashlight',
    'Multitool',
    'Solar-Powered Flashlight',
    'Hand Warmer',
    'Emergency Beacon',
    'Fire Starter',
    'Waterproof Match Case',
    'Paracord Bracelet',
    'Survival Whistle',
  ],
  food: [
    'Pizza',
    'Pasta',
    'Sushi',
    'Ramen',
    'Tacos',
    'Burritos',
    'Hamburgers',
    'Steak',
    'Salad',
    'Falafel',
    'Curry',
    'Paella',
    'Biryani',
    'Dim Sum',
    'Spring Rolls',
    'Pad Thai',
    'Pho',
    'Goulash',
    'Ratatouille',
    'Bouillabaisse',
    'Bratwurst',
    'Schnitzel',
    'Pierogi',
    'Gyros',
    'Souvlaki',
    'Lasagna',
    'Risotto',
    'Carbonara',
    'Chow Mein',
    'Peking Duck',
    'Kimchi',
    'Bibimbap',
    'Tteokbokki',
    'Samosas',
    'Butter Chicken',
    'Tandoori Chicken',
    'Shawarma',
    'Ceviche',
    'Empanadas',
    'Arepa',
    'Feijoada',
    'Poutine',
    'Beef Stroganoff',
    'Shepherd’s Pie',
    'Fish and Chips',
    'Scones',
    'Croissants',
    'Baguette',
    'Pretzels',
    'Sourdough Bread',
    'Focaccia',
    'Ciabatta',
    'Banana Bread',
    'Zucchini Bread',
    'Pumpkin Pie',
    'Cheesecake',
    'Tiramisu',
    'Gelato',
    'Mochi',
    'Baklava',
    'Churros',
    'Flan',
    'Pavlova',
    'Macarons',
    'Eclairs',
    'Creme Brulee',
    'Apple Pie',
    'Brownies',
    'Cupcakes',
    'Doughnuts',
    'Pancakes',
    'Waffles',
    'French Toast',
    'Omelette',
    'Quiche',
    'Frittata',
    'Shakshuka',
    'Hummus',
    'Baba Ganoush',
    'Tabbouleh',
    'Guacamole',
    'Salsa',
    'Tom Yum',
    'Miso Soup',
    'Gazpacho',
    'Clam Chowder',
    'Borscht',
    'Minestrone',
    'French Onion Soup',
    'Lentil Soup',
    'Chicken Noodle Soup',
    'Beef Stew',
    'Ratatouille',
    'Jambalaya',
    'Gumbo',
    'Pastrami on Rye',
    'Reuben Sandwich',
    'Monte Cristo',
    'BLT',
    'Grilled Cheese',
    'Club Sandwich',
    'Panini',
    'Falafel Wrap',
    'Kebab',
    'Satay',
    'Yakitori',
    'Fish Tacos',
    'Carnitas',
    'Barbecue Ribs',
    'Pulled Pork',
    'Fried Chicken',
    'Roast Beef',
    'Lamb Chops',
    'Grilled Salmon',
    'Fish and Chips',
    'Sushi Rolls',
    'Nigiri',
    'Sashimi',
    'Tempura',
    'Edamame',
    'Dumplings',
    'Spring Rolls',
    'Egg Rolls',
    'Stir Fry',
    'Fried Rice',
    'Lo Mein',
    'Kung Pao Chicken',
    'General Tso’s Chicken',
    'Sweet and Sour Pork',
    'Orange Chicken',
    'Mongolian Beef',
    'Mapo Tofu',
    'Chicken Tikka Masala',
    'Rogan Josh',
    'Vindaloo',
    'Dal Makhani',
    'Saag Paneer',
    'Naan',
    'Roti',
    'Paratha',
    'Dosa',
    'Idli',
    'Samosas',
    'Bhaji',
    'Chaat',
    'Pakoras',
    'Gulab Jamun',
    'Jalebi',
    'Rasgulla',
    'Kulfi',
    'Tzatziki',
    'Moussaka',
    'Spanakopita',
    'Souvlaki',
    'Dolma',
    'Baklava',
    'Feta Cheese',
    'Olives',
    'Greek Salad',
    'Hummus',
    'Tabbouleh',
    'Falafel',
    'Shawarma',
  ],
  music: [
    'Rock',
    'Pop',
    'Hip-Hop',
    'R&B',
    'Jazz',
    'Blues',
    'Country',
    'Classical',
    'Electronic',
    'Dance',
    'Reggae',
    'Folk',
    'Soul',
    'Metal',
    'Punk',
    'Gospel',
    'Opera',
    'Ska',
    'Funk',
    'Disco',
    'Techno',
    'House',
    'Trance',
    'Dubstep',
    'Drum and Bass',
    'Ambient',
    'Indie',
    'Alternative',
    'Grunge',
    'New Wave',
    'Synth-pop',
    'Psychedelic',
    'Progressive Rock',
    'Hard Rock',
    'Heavy Metal',
    'Death Metal',
    'Black Metal',
    'Thrash Metal',
    'Glam Rock',
    'Folk Rock',
    'Punk Rock',
    'Post-Punk',
    'Industrial',
    'Gothic',
    'Emo',
    'Screamo',
    'Shoegaze',
    'Lo-fi',
    'Garage Rock',
    'Latin',
    'Reggaeton',
    'Salsa',
    'Bachata',
    'Merengue',
    'Cumbia',
    'Bossa Nova',
    'Samba',
    'Tango',
    'Flamenco',
    'Afrobeat',
    'Highlife',
    'Soukous',
    'K-pop',
    'J-pop',
    'C-pop',
    'Trot',
    'Enka',
    'Mandopop',
    'Bollywood',
    'Indian Classical',
    'Ghazal',
    'Qawwali',
    'Sufi Music',
    'Arabesque',
    'Rai',
    'Fado',
    'Klezmer',
    'Polka',
    'Celtic',
    'Appalachian',
    'Bluegrass',
    'Old-Time',
    'Zydeco',
    'Cajun',
    'Calypso',
    'Soca',
    'Chutney',
    'Baila',
    'Dangdut',
    'Gamelan',
    'Javanese Classical',
    'Balinese Music',
    'Baroque',
    'Romantic',
    'Classical Period',
    'Renaissance Music',
    'Medieval Music',
    'Contemporary Classical',
    'Avant-Garde',
    'Experimental',
    'Noise Music',
    'Minimalism',
    'Electroacoustic',
    'Choral',
    'Gregorian Chant',
    'Madrigal',
    'Opera',
    'Orchestral',
    'Symphony',
    'Chamber Music',
    'Sonata',
    'Concerto',
    'Aria',
    'Lied',
    'Art Song',
    'Musical Theatre',
    'Broadway',
    'Film Score',
    'Video Game Music',
    'Anime Soundtracks',
    'Jingle',
    'Theme Music',
    'Doo-wop',
    'Motown',
    'Rhythm and Blues',
    'Soul Music',
    'Disco',
    'Funk',
    'Gospel',
    'Spirituals',
    'Work Songs',
    'Jazz Fusion',
    'Bebop',
    'Swing',
    'Ragtime',
    'Dixieland',
    'Acid Jazz',
    'Smooth Jazz',
    'Free Jazz',
    'Modal Jazz',
    'Hard Bop',
    'Cool Jazz',
    'West Coast Jazz',
    'Chicago Blues',
    'Delta Blues',
    'Electric Blues',
    'Country Blues',
    'Blues Rock',
    'Piedmont Blues',
    'Soul Blues',
    'Jump Blues',
    'Boogie-woogie',
    'Country and Western',
    'Nashville Sound',
    'Outlaw Country',
    'Alt-Country',
    'Americana',
    'Texas Country',
    'Red Dirt',
    'Bluegrass',
    'Country Rock',
    'Country Pop',
    'Honky Tonk',
    'Bakersfield Sound',
    'Western Swing',
    'Cajun Music',
    'Zydeco',
    'Tex-Mex',
    'Mariachi',
    'Norteño',
    'Ranchera',
    'Corrido',
    'Grupero',
    'Banda',
    'Duranguense',
    'Tejano',
    'Christian Music',
    'Contemporary Christian',
    'Gospel',
  ],
  fitness: [
    'Aerobics',
    'Pilates',
    'Yoga',
    'Tai Chi',
    'CrossFit',
    'Bodybuilding',
    'Weightlifting',
    'Powerlifting',
    'High-Intensity Interval Training (HIIT)',
    'Low-Intensity Steady State (LISS)',
    'Tabata',
    'Circuit Training',
    'Kickboxing',
    'Boxing',
    'Mixed Martial Arts (MMA)',
    'Karate',
    'Judo',
    'Brazilian Jiu-Jitsu',
    'Taekwondo',
    'Kung Fu',
    'Krav Maga',
    'Muay Thai',
    'Wrestling',
    'Fencing',
    'Parkour',
    'Running',
    'Jogging',
    'Sprinting',
    'Marathon Training',
    'Trail Running',
    'Cycling',
    'Mountain Biking',
    'Spinning',
    'Swimming',
    'Water Aerobics',
    'Rowing',
    'Canoeing',
    'Kayaking',
    'Stand Up Paddleboarding (SUP)',
    'Surfing',
    'Rock Climbing',
    'Bouldering',
    'Hiking',
    'Trekking',
    'Backpacking',
    'Skiing',
    'Snowboarding',
    'Ice Skating',
    'Roller Skating',
    'Inline Skating',
    'Skateboarding',
    'BMX',
    'Motocross',
    'Horseback Riding',
    'Equestrian',
    'Pole Dancing',
    'Ballet Workout',
    'Dance Fitness',
    'Zumba',
    'Belly Dancing',
    'Hip Hop Dance',
    'Salsa Dancing',
    'Ballroom Dancing',
    'Tango Dancing',
    'Capoeira',
    'Gymnastics',
    'Trampolining',
    'Calisthenics',
    'Street Workout',
    'Functional Training',
    'Animal Flow',
    'Mobility Training',
    'Flexibility Training',
    'Stretching',
    'Foam Rolling',
    'Plyometrics',
    'Jump Rope',
    'Hula Hooping',
    'Barre Workout',
    'Core Training',
    'Kettlebell Training',
    'Sandbag Training',
    'Medicine Ball Exercises',
    'Resistance Band Training',
    'Suspension Training (TRX)',
    'Aquatic Fitness',
    'Underwater Workout',
    'Nordic Walking',
    'Racquet Sports (Tennis, Badminton, Squash)',
    'Golf Fitness',
    'Ski Fitness',
    'Snowboard Fitness',
    'Martial Arts Conditioning',
    'Boxing Conditioning',
    'Basketball Fitness',
    'Soccer Fitness',
    'Football Fitness',
    'Baseball Fitness',
    'Volleyball Fitness',
    'Rugby Fitness',
    'Lacrosse Fitness',
    'Field Hockey Fitness',
    'Cricket Fitness',
    'Track and Field Training',
    'Olympic Weightlifting',
    'Strongman Training',
    'Bodyweight Training',
    'Outdoor Fitness',
    'Adventure Racing Training',
    'Triathlon Training',
    'Duathlon Training',
    'Ironman Training',
    'Parasport Fitness',
    'Senior Fitness',
    'Youth Fitness',
    'Postnatal Fitness',
    'Prenatal Fitness',
    'Rehabilitative Exercise',
    'Physical Therapy Exercises',
    'Occupational Therapy Exercises',
    'Corrective Exercise',
    'Posture Improvement',
    'Balance Training',
    'Coordination Training',
    'Speed and Agility Training',
    'Sport-Specific Training',
    'Military Fitness',
    'Police Academy Training',
    'Firefighter Fitness',
    'First Responder Fitness',
    'Corporate Wellness Programs',
    'Group Fitness Classes',
    'Personal Training',
    'Online Fitness Coaching',
    'Virtual Reality Fitness',
    'Exergaming',
    'Fitness Boot Camps',
    'Outdoor Boot Camps',
    'Indoor Cycling Classes',
    'Mindfulness and Meditation',
    'Breathwork for Fitness',
    'Qi Gong',
    'Alexander Technique',
    'Feldenkrais Method',
    'Biohacking for Fitness',
    'Nutrition and Fitness Coaching',
    'Sports Nutrition',
    'Hydration Strategies',
    'Supplement Use in Fitness',
    'Recovery Techniques',
    'Cold Therapy',
    'Heat Therapy',
    'Compression Therapy',
    'Massage Therapy',
    'Acupuncture for Athletes',
    'Chiropractic Care for Fitness',
    'Injury Prevention in Fitness',
  ],
  automobile: [
    'Sedan',
    'Hatchback',
    'SUV',
    'Crossover',
    'Coupe',
    'Convertible',
    'Sports Car',
    'Luxury Car',
    'Electric Vehicle (EV)',
    'Hybrid Car',
    'Plug-in Hybrid',
    'Pickup Truck',
    'Van',
    'Minivan',
    'Station Wagon',
    'Limousine',
    'Off-Road Vehicle',
    'Racing Car',
    'Formula One Car',
    'Rally Car',
    'Drift Car',
    'Classic Car',
    'Vintage Car',
    'Muscle Car',
    'Pony Car',
    'Super Car',
    'Hyper Car',
    'Concept Car',
    'Self-Driving Car',
    'Autonomous Vehicle',
    'Fuel Cell Vehicle',
    'Diesel Car',
    'Gasoline Car',
    'Bi-fuel Vehicle',
    'Flex-Fuel Vehicle',
    'Natural Gas Vehicle',
    'Propane Vehicle',
    'Solar Car',
    'Steam Car',
    'Microcar',
    'City Car',
    'Kei Car',
    'Tuner Car',
    'Lowrider',
    'Hot Rod',
    'Street Rod',
    'Dragster',
    'Monster Truck',
    'Amphibious Vehicle',
    'Recreational Vehicle (RV)',
    'Camper Van',
    'Motorhome',
    'Caravan',
    'Overland Vehicle',
    'Hearse',
    'Police Car',
    'Fire Engine',
    'Ambulance',
    'Taxi',
    'Ride-Sharing Vehicle',
    'Livery Vehicle',
    'Shuttle Bus',
    'School Bus',
    'Tour Bus',
    'Articulated Bus',
    'Double Decker Bus',
    'Trolleybus',
    'Tram',
    'Train',
    'High-Speed Rail',
    'Maglev Train',
    'Light Rail Vehicle',
    'Subway Car',
    'Freight Train',
    'Tank Car',
    'Boxcar',
    'Flatcar',
    'Gondola Car',
    'Hopper Car',
    'Reefer Car',
    'Stock Car',
    'Well Car',
    'Caboose',
    'Handcar',
    'Maintenance of Way Equipment',
    'Railcar Mover',
    'Snowplow',
    'Street Sweeper',
    'Garbage Truck',
    'Dump Truck',
    'Cement Mixer',
    'Crane Truck',
    'Flatbed Truck',
    'Refrigerated Truck',
    'Tanker Truck',
    'Tow Truck',
    'Utility Truck',
    'Box Truck',
    'Delivery Van',
    'Panel Van',
    'Step Van',
    'Cargo Van',
    'Passenger Van',
    'Shuttle Van',
    'Minibus',
    'Coach Bus',
    'Charter Bus',
    'Airport Shuttle',
    'Tourist Coach',
    'Party Bus',
    'School Bus',
    'Transit Bus',
    'Intercity Bus',
    'Articulated Bus',
    'Double-Decker Bus',
    'Low-Floor Bus',
    'Trolleybus',
    'Battery Electric Bus',
    'Hybrid Electric Bus',
    'Fuel Cell Bus',
    'CNG Bus',
    'LNG Bus',
    'Biodiesel Bus',
    'Alcohol Bus',
    'Steam Bus',
    'Horse-Drawn Bus',
    'Pedal Bus',
    'Motorcycle',
    'Scooter',
    'Moped',
    'Dirt Bike',
    'Touring Motorcycle',
    'Cruiser Motorcycle',
    'Sport Bike',
    'Adventure Bike',
    'Enduro Bike',
    'Motocross Bike',
    'Track Racing Bike',
    'Trike',
    'Sidecar',
    'Quad Bike',
    'Snowmobile',
    'Jet Ski',
    'Hovercraft',
    'ATV',
    'UTV',
    'Golf Cart',
    'Go-Kart',
    'Dune Buggy',
    'Sand Rail',
    'Race Car',
    'Drag Car',
    'Drift Car',
    'Rally Car',
    'Stock Car',
    'Touring Car',
    'Formula Car',
    'Open-Wheel Car',
    'Prototype Car',
    'GT Car',
    'Sports Prototype',
    'Can-Am Car',
    'Le Mans Prototype',
    'Group C Car',
    'GTP Car',
    'IMSA GTO',
    'Trans-Am Car',
    'NASCAR Car',
    'IndyCar',
    'Formula E Car',
  ],
};

async function addNewKeywords() {
  let duplicateCount = 0;
  for (const category in newKeywords) {
    for (const value of newKeywords[category]) {
      const existingKeyword =
        await prisma.keyword.findFirst({
          where: {
            category,
            value: {
              equals: value,
              mode: 'insensitive',
            },
          },
        });

      if (existingKeyword) {
        console.log(
          `Duplicate found and skipped: ${value} in ${category}`,
        );
        duplicateCount++;
      } else {
        await prisma.keyword.create({
          data: {
            category,
            value,
            level: 2,
          },
        });
        console.log(
          `Added new keyword: ${value} in ${category}`,
        );
      }
    }
  }
  console.log(
    `New keywords have been added. Duplicates skipped: ${duplicateCount}`,
  );
}

async function main() {
  try {
    await addNewKeywords();
  } catch (e) {
    console.error(
      'Error adding new keywords:',
      e.message,
    );
  } finally {
    await prisma.$disconnect();
  }
}

main();
