export default [
    // { value: 'Sports', label: 'Sports' },
    // { value: 'travel', label: 'travel' },
    // { value: 'hobbies', label: 'hobbies' },
    // { value: 'Lifestyle', label: 'Lifestyle' },
    // { value: 'food', label: 'food' },
    // { value: 'entertainment', label: 'entertainment' },
    // { value: 'events', label: 'events' },
    // { value: 'Restaurants', label: 'Restaurants' },

    // { value: 'Fielding', label: 'Fielding' },
    // { value: 'Underwater', label: 'Underwater' },
    // { value: 'Recipes', label: 'Recipes' },
    // { value: 'brunch', label: 'brunch' },
    // { value: 'Fitness', label: 'Fitness' },
    // { value: 'Diet', label: 'Diet' },

    { value: 'Role', label: 'Occupation-Role' }, { value: 'Position', label: 'Occupation-Position' }, { value: 'Duty', label: 'Occupation-Duty' }, { value: 'Profession', label: 'Occupation-Profession' }, { value: 'Craft', label: 'Occupation-Craft' }, { value: 'Business', label: 'Occupation-Business' }, { value: 'Livelihood', label: 'Occupation-Livelihood' }, { value: 'Avocation', label: 'Occupation-Avocation' }, { value: 'Vocation ', label: 'Occupation-Vocation ' }, { value: 'Appointment', label: 'Occupation-Appointment' }, { value: 'Job', label: 'Occupation-Job' },
    { value: 'Nuclear', label: 'Family Details-Nuclear' }, { value: 'Joint', label: 'Family Details-Joint' }, { value: 'Siblings', label: 'Family Details-Siblings' }, { value: 'Children', label: 'Family Details-Children' }, { value: 'Grandparents', label: 'Family Details-Grandparents' }, { value: 'Aunt & Uncle', label: 'Family Details-Aunt & Uncle' }, { value: 'Cousins', label: 'Family Details-Cousins' }, { value: 'Relatives', label: 'Family Details-Relatives' }, { value: 'Love', label: 'Family Details-Love' }, { value: 'Friendship', label: 'Family Details-Friendship' }, { value: 'Care_giver', label: 'Family Details-Care-giver' }, { value: 'daughter_in_law', label: 'Family Details-daughter-in-law' }, { value: 'mother_in_law', label: 'Family Details-mother-in-law' }, { value: 'father_in_law', label: 'Family Details-father-in-law' }, { value: 'sister_in_law', label: 'Family Details-sister-in-law' }, { value: 'divorce', label: 'Family Details-divorce' }, { value: 'engaged', label: 'Family Details-engaged' }, { value: 'ex_husband', label: 'Family Details-ex-husband' }, { value: 'ex_wife', label: 'Family Details-ex-wife' }, { value: 'half_brother', label: 'Family Details-half-brother' }, { value: 'half_sister', label: 'Family Details-half-sister' }, { value: 'step_brother', label: 'Family Details-step-brother' }, { value: 'step_sister', label: 'Family Details-step-sister' }, { value: 'kin', label: 'Family Details-kin' }, { value: 'next_to_kin', label: 'Family Details-next-to-kin' }, { value: 'single', label: 'Family Details-single' }, { value: 'twins', label: 'Family Details-twins' }, { value: 'offspring', label: 'Family Details-offspring' },
    { value: 'Automatic', label: 'Vehicle Details-Automatic' }, { value: 'Fuel Efficiency', label: 'Vehicle Details-Fuel Efficiency' }, { value: 'Safety', label: 'Vehicle Details-Safety' }, { value: 'Upgradable', label: 'Vehicle Details-Upgradable' }, { value: 'Ownership', label: 'Vehicle Details-Ownership' }, { value: 'Maintenance Requirements', label: 'Vehicle Details-Maintenance Requirements' }, { value: 'Environment Impact', label: 'Vehicle Details-Environment Impact' }, { value: 'Insurances', label: 'Vehicle Details-Insurances' }, { value: 'Vehicle Identification Number', label: 'Vehicle Details-Vehicle Identification Number' }, { value: 'License', label: 'Vehicle Details-License' }, { value: 'Registration Fees', label: 'Vehicle Details-Registration Fees' }, { value: 'Taxation', label: 'Vehicle Details-Taxation' }, { value: 'Bicycle', label: 'Vehicle Details-Bicycle' }, { value: 'Motorcycle', label: 'Vehicle Details-Motorcycle' }, { value: 'Car', label: 'Vehicle Details-Car' }, { value: 'Pickup truck', label: 'Vehicle Details-Pickup truck' }, { value: 'Scooters', label: 'Vehicle Details-Scooters' }, { value: 'Boat', label: 'Vehicle Details-Boat' }, { value: 'Yacht', label: 'Vehicle Details-Yacht' }, { value: 'Two wheeler', label: 'Vehicle Details-Two wheeler' }, { value: 'Four wheeler', label: 'Vehicle Details-Four wheeler' },
    { value: 'Mental Health', label: 'Health-Mental Health' }, { value: 'Physical Health', label: 'Health-Physical Health' }, { value: 'Fitness', label: 'Health-Fitness' }, { value: 'Nutrition', label: 'Health-Nutrition' }, { value: 'Exercise', label: 'Health-Exercise' }, { value: 'Sleep', label: 'Health-Sleep' }, { value: 'Diet', label: 'Health-Diet' }, { value: 'Paleo', label: 'Health-Paleo' }, { value: 'Vegan', label: 'Health-Vegan' }, { value: 'Low_Carb', label: 'Health-Low-Carb' }, { value: 'Dukan', label: 'Health-Dukan' }, { value: 'Ultra_Low_Fat', label: 'Health-Ultra-Low-Fat' }, { value: 'Atkins', label: 'Health-Atkins' }, { value: 'HCG', label: 'Health-HCG' }, { value: 'Fasting', label: 'Health-Fasting' }, { value: 'Intermittent', label: 'Health-Intermittent' }, { value: 'Phycology', label: 'Health-Phycology' },
    { value: 'Research', label: 'Social Media-Networking' }, { value: 'Research', label: 'Social Media-Research' }, { value: 'Review', label: 'Social Media-Review' }, { value: 'Creation', label: 'Social Media-Creation' }, { value: 'Image sharing', label: 'Social Media-Image sharing' }, { value: 'video sharing', label: 'Social Media-video sharing' }, { value: 'Engagement', label: 'Social Media-Engagement' }, { value: 'Community', label: 'Social Media-Community' }, { value: 'Blogs', label: 'Social Media-Blogs' }, { value: 'Vlogs', label: 'Social Media-Vlogs' }, { value: 'Discussion Platform', label: 'Social Media-Discussion Platform' },
    { value: 'Cuisine', label: 'Food & Restaurants-Cuisine' }, { value: 'North Indian', label: 'Food & Restaurants-North Indian' }, { value: 'South Indian', label: 'Food & Restaurants-South Indian' }, { value: 'North Eastern', label: 'Food & Restaurants-North Eastern' }, { value: 'Cooking', label: 'Food & Restaurants-Cooking' }, { value: 'Recipes', label: 'Food & Restaurants-Recipes' }, { value: 'Snack', label: 'Food & Restaurants-Snack' }, { value: 'Lunch', label: 'Food & Restaurants-Lunch' }, { value: 'breakfast', label: 'Food & Restaurants-breakfast' }, { value: 'dinner', label: 'Food & Restaurants-dinner' }, { value: 'brunch', label: 'Food & Restaurants-brunch' }, { value: 'diet', label: 'Food & Restaurants-diet' }, { value: 'organic', label: 'Food & Restaurants-organic' }, { value: 'delivery takeaway', label: 'Food & Restaurants-delivery takeaway' }, { value: 'culinary', label: 'Food & Restaurants-culinary' }, { value: 'flyovers', label: 'Food & Restaurants-flyovers' }, { value: 'foodie', label: 'Food & Restaurants-foodie' }, { value: 'food culture', label: 'Food & Restaurants-food culture' }, { value: 'comfort food', label: 'Food & Restaurants-comfort food' }, { value: 'street food', label: 'Food & Restaurants-street food' }, { value: 'fast food', label: 'Food & Restaurants-fast food' },
    { value: 'Area', label: 'Location-Area' }, { value: 'PIN Code', label: 'Location-PIN Code' }, { value: 'home', label: 'Location-home' }, { value: 'Address', label: 'Location-Address' }, { value: 'Street Address', label: 'Location-Street Address' }, { value: 'Postal Code', label: 'Location-Postal Code' }, { value: 'Locality', label: 'Location-Locality' }, { value: 'City', label: 'Location-City' }, { value: 'State', label: 'Location-State' }, { value: 'Landmarks', label: 'Location-Landmarks' },
    { value: 'Trip', label: 'Travel-Trip' }, { value: 'Business Trip', label: 'Travel-Business Trip' }, { value: 'Exploration', label: 'Travel-Exploration' }, { value: 'Holiday', label: 'Travel-Holiday' }, { value: 'Vacation', label: 'Travel-Vacation' }, { value: 'Sightseeing', label: 'Travel-Sightseeing' }, { value: 'Getaway', label: 'Travel-Getaway' }, { value: 'Destination', label: 'Travel-Destination' }, { value: 'Journey', label: 'Travel-Journey' }, { value: 'Hotel', label: 'Travel-Hotel' }, { value: 'tickets', label: 'Travel-tickets' }, { value: 'air ticket', label: 'Travel-air ticket' }, { value: 'train', label: 'Travel-train' }, { value: 'taxi', label: 'Travel-taxi' }, { value: 'airfare', label: 'Travel-airfare' }, { value: 'package', label: 'Travel-package' }, { value: 'budget travel', label: 'Travel-budget travel' },
    { value: 'Car insurance', label: 'Insurance-Car insurance' }, { value: 'insurance quotes', label: 'Insurance-insurance quotes' }, { value: 'auto', label: 'Insurance-auto' }, { value: 'public liability', label: 'Insurance-public liability' }, { value: 'insurance agents', label: 'Insurance-insurance agents' }, { value: 'business insurance', label: 'Insurance-business insurance' }, { value: 'broker', label: 'Insurance-broker' }, { value: 'policy', label: 'Insurance-policy' }, { value: 'insurance policy', label: 'Insurance-insurance policy' }, { value: 'risk', label: 'Insurance-risk' }, { value: 'coverage', label: 'Insurance-coverage' }, { value: 'premiums', label: 'Insurance-premiums' }, { value: 'claims', label: 'Insurance-claims' }, { value: 'liabilities', label: 'Insurance-liabilities' }, { value: 'financial security', label: 'Insurance-financial security' }, { value: 'safety', label: 'Insurance-safety' }, { value: 'investments', label: 'Insurance-investments' }, { value: 'assurance', label: 'Insurance-assurance' },
    { value: 'Debit', label: 'Cards-Debit' }, { value: 'Credit', label: 'Cards-Credit' }, { value: 'Prepaid', label: 'Cards-Prepaid' }, { value: 'Electronic', label: 'Cards-Electronic' }, { value: 'Black', label: 'Cards-Black' }, { value: 'Platinum', label: 'Cards-Platinum' }, { value: 'Premium', label: 'Cards-Premium' }, { value: 'Reloadable', label: 'Cards-Reloadable' }, { value: 'Millennia', label: 'Cards-Millennia' }, { value: 'Forex', label: 'Cards-Forex' }, { value: 'Commercial Credit Card', label: 'Cards-Commercial Credit Card' }, { value: 'MasterCard', label: 'Cards-MasterCard' }, { value: 'Visa', label: 'Cards-Visa' }, { value: 'Luxury', label: 'Cards-Luxury' }, { value: 'American Express', label: 'Cards-American Express' }, { value: 'ATM Card', label: 'Cards-ATM Card' }, { value: 'Interest Rates', label: 'Cards-Interest Rates' }, { value: 'Payment Security', label: 'Cards-Payment Security' }, { value: 'Fraud Prevention', label: 'Cards-Fraud Prevention' },
    { value: 'Athletics', label: 'Sports-Athletics' }, { value: 'Team', label: 'Sports-Team' }, { value: 'Individual', label: 'Sports-Individual' }, { value: 'Extreme', label: 'Sports-Extreme' }, { value: 'Olympics', label: 'Sports-Olympics' }, { value: 'Common Wealth', label: 'Sports-Common Wealth' }, { value: 'Net', label: 'Sports-Net' }, { value: 'Fielding', label: 'Sports-Fielding' }, { value: 'Striking', label: 'Sports-Striking' }, { value: 'Target', label: 'Sports-Target' }, { value: 'Animal', label: 'Sports-Animal' }, { value: 'Underwater', label: 'Sports-Underwater' }, { value: 'Mind', label: 'Sports-Mind' }, { value: 'Martial Arts', label: 'Sports-Martial Arts' }, { value: 'Air', label: 'Sports-Air' }, { value: 'Adventure', label: 'Sports-Adventure' }, { value: 'Golf', label: 'Sports-Golf' },
    { value: 'Conferences', label: 'Events-Conferences' }, { value: 'Trade', label: 'Events-Trade' }, { value: 'Networking', label: 'Events-Networking' }, { value: 'Workshops', label: 'Events-Workshops' }, { value: 'Team Building', label: 'Events-Team Building' }, { value: 'Product Launch', label: 'Events-Product Launch' }, { value: 'Charity', label: 'Events-Charity' }, { value: 'Internal Corporate Events', label: 'Events-Internal Corporate Events' }, { value: 'Weddings', label: 'Events-Weddings' }, { value: 'Engagements', label: 'Events-Engagements' }, { value: 'Parties', label: 'Events-Parties' }, { value: 'Ball', label: 'Events-Ball' }, { value: 'Banquets', label: 'Events-Banquets' }, { value: 'Birthday', label: 'Events-Birthday' }, { value: 'Dinner', label: 'Events-Dinner' }, { value: 'Garden', label: 'Events-Garden' }, { value: 'Cocktail', label: 'Events-Cocktail' }, { value: 'Tea', label: 'Events-Tea' }, { value: 'Celebration', label: 'Events-Celebration' }, { value: 'Occasion', label: 'Events-Occasion' }, { value: 'Festival', label: 'Events-Festival' }, { value: 'Music', label: 'Events-Music' }, { value: 'Concerts', label: 'Events-Concerts' }, { value: 'Ceremony', label: 'Events-Ceremony' }, { value: 'Reception', label: 'Events-Reception' }, { value: 'Formal', label: 'Events-Formal' }, { value: 'Carnival', label: 'Events-Carnival' }, { value: 'Symposium', label: 'Events-Symposium' }, { value: 'Summit', label: 'Events-Summit' }, { value: 'Exposition', label: 'Events-Exposition' }, { value: 'Expo', label: 'Events-Expo' }, { value: 'Auto_Expo', label: 'Events-Auto-Expo' }, { value: 'Fair', label: 'Events-Fair' }, { value: 'Gala', label: 'Events-Gala' }, { value: 'Get_together', label: 'Events-Get-together' }, { value: 'Jubilee', label: 'Events-Jubilee' }, { value: 'Meet', label: 'Events-Meet' }, { value: 'Outing', label: 'Events-Outing' }, { value: 'Parade', label: 'Events-Parade' }, { value: 'rally', label: 'Events-rally' }, { value: 'soiree', label: 'Events-soiree' }, { value: 'tournament', label: 'Events-tournament' }, { value: 'reunion', label: 'Events-reunion' },
    { value: 'Salary', label: 'Income Sources-Salary' }, { value: 'Revenue', label: 'Income Sources-Revenue' }, { value: 'Profit', label: 'Income Sources-Profit' }, { value: 'Earning', label: 'Income Sources-Earning' }, { value: 'Credit Score', label: 'Income Sources-Credit Score' }, { value: 'Wages', label: 'Income Sources-Wages' }, { value: 'Bankroll', label: 'Income Sources-Bankroll' }, { value: 'Tips', label: 'Income Sources-Tips' }, { value: 'Funds', label: 'Income Sources-Funds' }, { value: 'Trust', label: 'Income Sources-Trust' }, { value: 'Expenses', label: 'Income Sources-Expenses' }, { value: 'Expenditure', label: 'Income Sources-Expenditure' }, { value: 'Budgeting', label: 'Income Sources-Budgeting' }, { value: 'Savings', label: 'Income Sources-Savings' }, { value: 'Benefits', label: 'Income Sources-Benefits' }, { value: 'Influx', label: 'Income Sources-Influx' }, { value: 'inflow', label: 'Income Sources-inflow' }, { value: 'CTC', label: 'Income Sources-CTC' }, { value: 'Tax', label: 'Income Sources-Tax' }, { value: 'Returns', label: 'Income Sources-Returns' },


]

