# monstache.toml
# connect to MongoDB using the following URL
mongo-url = "mongodb://mongo:example@server-mongo-1/eaProfiling?authSource=admin&connect=direct"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://elasticsearch:9200"]

# if you need to seed an index from a collection and not just listen and sync changes events
# you can copy entire collections or views from MongoDB to Elasticsearch
change-stream-namespaces = ["eaProfiling.keywords","eaProfiling.customers"]
direct-read-namespaces = ["eaProfiling.keywords","eaProfiling.customers"]


# # Direct mapping: Syncing 'keywords' collection in MongoDB to 'keywords' in Elasticsearch
# [[mapping]]
# namespace = "eaProfiling.keywords"
# index = "keywords"
# type = "keyword"
#
# [[script]]
# namespace = "eaProfiling.keywords"
# path = "/usr/monstache/keywords.js"
# routing = true

# connection settings


# [logs]
# error = "./logs/error.log"
# info = "./logs/info.log"
# warn = "./logs/warn.log"
# trace = "./logs/trace.log"
